version: "3"
services:
  nginx:
    ports:
      - "80:80" # 80 : 80 port nginx
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER} #truyen bien MONGO_USER -> environment trong container -> config.js se lay o env
      - MONGO_PASSWORD=${MONGO_PASSWORD} #truyen bien MONGO_PASSWORD -> environment trong container -> config.js se lay o env
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
