version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80" # 3000 port nodejs : 80 port nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    image: teddykul/node-app-example #name app at docker hub
    environment:
      - PORT=3000
    depends_on:
      - mongo #phu thuoc vao container mongo -> khi up lai thi mongo se start truoc
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis #Save section and cookie
volumes:
  mongo-db:
